name: deploy-book

on:
  push

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/book
      with:
        target-branch: "draft"
